/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : rowcoaching

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2017-07-07 13:14:42
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for saillingcrews
-- ----------------------------
DROP TABLE IF EXISTS `saillingcrews`;
CREATE TABLE `saillingcrews` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `shortname` varchar(255) DEFAULT NULL,
  `club` int(11) DEFAULT NULL,
  `description` text,
  `tracker_id` int(11) DEFAULT NULL,
  `flag_image` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of saillingcrews
-- ----------------------------
INSERT INTO `saillingcrews` VALUES ('1', 'International Yacht Club Amsterdam', 'IYCA', null, 'De International Yacht Club Amsterdam is opgericht door een aantal fanatiek (zee-)zeilende zakenmensen uit Amsterdam en omstreken. De International Yacht Club Amsterdam is gevestigd in het 5-sterren Grand Hotel Amrâth aan de Prins Hendrikkade, in het centrum van Amsterdam. Dit statige pand stond vroeger bekend als het “Scheepvaarthuys” en is, gelegen aan de oevers van het IJ, dé ideale plek voor een gezellige, maritieme sociëteit.', '1', 'IYCA.png');
INSERT INTO `saillingcrews` VALUES ('2', 'Jachtclub Scheveningen', 'JS', null, 'Jachtclub Scheveningen is opgericht in 1973 en is daarmee de eerste Jachtclub die direct aan de Noordzee ligt. De jachtclub heeft ongeveer 600 leden, meest jachtzeilers. Het is dan ook niet verwonderlijk dat de meeste successen door leden behaald zijn op zee, zoals in de Fastnetrace (meerdere winnaars) de Arc, de Admirals Cup, de AZAB (Azoren and back) de Global Oceanrace de Whitbreadrace en natuurlijk de RORC North Sea Race.', '2', '2.DenHaag.png');
INSERT INTO `saillingcrews` VALUES ('3', 'KNZ&RV Muiden', 'KNZ&RV', null, 'De Koninklijke Nederlandsche Zeil- & Roeivereeniging is opgericht in 1847 en is de oudste watersportvereniging in Nederland. In haar geschiedenis heeft de KNZ&RV veelvuldig aan de wieg gestaan van belangrijke ontwikkelingen en initiatieven in de watersport. Het organiseren van wedstrijden is een belangrijke missie voor de vereniging. Daarnaast ondersteunt de Koninklijke waar mogelijk het gehandicapten-zeilen.', '3', '3.Muiden.png');
INSERT INTO `saillingcrews` VALUES ('4', 'KWS Sneek', 'KWS', null, 'De Koninklijke Watersportvereniging Sneek is voor de meeste mensen vooral bekend als organisator van de Sneekweek. Nog steeds het grootste ‘in shore’ internationale zeilevenement van Europa. Maar de KWS organiseert nog meer zeilevenementen, van clubwedstrijden tot NK’s, EK’s en WK’s. Veel bekende zeilers zijn lid van de KWS, te denken valt aan Pieter-Jan Postma, Dirk de Ridder, Brechtje van der Werf, Thijs Kort, Erik Kort, Tom Otte en vele anderen.', null, '4.Sneek_.png');
INSERT INTO `saillingcrews` VALUES ('5', 'KWV De Kaag', 'KWV', null, 'De vereniging is in 1910 opgericht met als doel het organiseren van zeil en roei wedstrijden. Bij de oprichting had de vereniging 59 leden. Inmiddels is het ledental gegroeid naar ongeveer 1600 leden. Wedstrijdzeilen is nog steeds een belangrijk onderdeel, maar ook motorbootvaarders en sloeproeiers maken tegenwoordig een belangrijk deel uit van de vereniging. De vereniging heeft op dit moment 3 jachthavens (met in totaal ongeveer 600 ligplaatsen). De trots is de Kaagsocieteit. Dit verenigingsgebouw staat vlak langs de plassen en is de uitvalbasis voor de landelijk bekende Kaagweek.', null, '5.Kaag_.png');
INSERT INTO `saillingcrews` VALUES ('6', 'R.R. & Z.V. Maas en Roer', 'R.R. & Z.V. Maas en Roer', null, 'De Roermondse Roei- en Zeilvereniging Maas en Roer is opgericht in 1909 en kent 592 leden. De vereniging is actief in het wedstrijdzeilen en heeft vele successen behaald. Prestaties van diverse leden zijn o.a. 2 wereldkampioenen, 7 Nederlandse kampioenen en een Duits/Belgisch/Zwitsers kampioen. De kampioenschappen zijn o.a. gevaren in de H-Boot, Randmeer, Yngling, Europe, Optimist, Melges24 en ORC1.', null, '6.Roermond.png');
INSERT INTO `saillingcrews` VALUES ('7', 'WV Uitdam', 'WV Uitdam', null, 'WV Uitdam is nog steeds een vereniging die de wedstrijdorganisatie ter harte gaat. Niet meer, zoals voorheen, daadwerkelijk Wereldkampioenschappen en klasse-wedstrijden organiseren, maar assisteren bij andere evenementen. Het verstrekken van adviezen en indien noodzakelijk daadwerkelijke hulp. WV Uitdam is een vereniging die begrijpt dat een wedstrijdzeiler in veel gevallen geen binding heeft met zijn eigen club. Hij/zij is tenslotte meestal elders aan het wedstrijdzeilen. Voor dergelijke zeilers is er ook een plek bij Uitdam.', null, '7.Uitdam.png');
INSERT INTO `saillingcrews` VALUES ('8', 'VWDTP', 'VWDTP', null, 'Vereniging Watersport De Twee Provincien (VWDTP), is een actieve vereniging in noorden van het land. Het Paterswoldsemeer is het thuiswater, aan de rand van Groningen.Het Paterswoldse meer ligt in zowel provincie Drenthe, als Groningen, vandaar de twee provincien. Met rond de 900 leden is het een grote actieve vereniging die zich met name richt op wedstrijdzeilen en opleiding van zowel de jeugd als volwassenen, zowel lokaal, als regionaal. De belangrijkste klassen zijn de laser, optimist, sailhorse, 16m2 en valk.', null, '8.Groningen.png');
INSERT INTO `saillingcrews` VALUES ('9', 'WV Almere Centraal', 'WV Almere Centraal', null, 'Opgericht in 1980 door een aantal fanatieke surfers van het eerste uur. Er werd gesurft bij het Zilverstrand. In 2012 is de vereniging begonnen met een nieuw progamma. Stimuleren van een dagelijks sport- en beweegaanbod voor scholieren. Ruim 300 kinderen tot 18 jaar hebben een surf clinic gevolgd. In 2012 is Almere Centraal ook uitgeroepen als beste club tijdens de North Sea Cup (Engeland, Noord Frankrijk, Belgie). Almere Centraal is de landskampioen Eredivisie Zeilen 2016.', null, '9.AlmereCentr.png');
INSERT INTO `saillingcrews` VALUES ('10', 'WSV Almere Haven', 'WSV Almere Haven', null, 'De WSV Almere Haven heeft ruim 600 leden die actief met watersport bezig zijn. Hiervan is ongeveer de helft motorboot-vaarder en de andere helft zeiler. Door diverse commissies worden evenementen en wedstrijden georganiseerd. Waar motorbootvaarders zich richten op toer- en langere tochten, richten de zeilers zich meer op wedstrijden en toertochten in groeps-of teamverband.  Watersport Vereniging Almere Haven verzorgt vele evenementen voor alle leden.\r\nDe zeilers varen onder andere de Avondcompetitie, tijdens het seizoen wekelijks op dinsdag- of donderdagavond. Door de zeilcommissie van WSV Almere Haven worden ook regionale en landelijke wedstrijden worden georganiseerd.', null, '10.AlmereHaven.png');
INSERT INTO `saillingcrews` VALUES ('11', 'WSV Flevomare', 'WSV Flevomare', null, 'WSV Flevomare uit Almere is opgericht op 11 maart 1992 en kent op dit moment 144 leden. Het merendeel van de leden van WSV Flevomare bezit een kajuitzeiljacht en zijn actief in de ORC-klassen. WSV Flevomare is organisator van de Almere Regatta.', null, '11.Flevomare.png');
INSERT INTO `saillingcrews` VALUES ('12', 'WSV Giesbeek', 'WSV Giesbeek', null, 'WSV Giesbeek, de watersportvereniging van Giesbeek, werd op 5 november 1969 opgericht door een aantal enthousiaste watersporters. Gedurende haar bestaan heeft de vereniging een constante groei van het aantal leden gekend; tegenwoordig heeft Watersportvereniging Giesbeek ca. 1450 leden, een aantal dat ook heden ten dage nog steeds groeit. Zij behoort daarmee tot de vier grootste watersportverenigingen van Nederland.', null, '12.Giesbeek.png');
INSERT INTO `saillingcrews` VALUES ('13', 'WSHeeg', 'WSHeeg', null, 'WaterSportvereniging Heeg is opgericht in 1967 en kent op dit moment 450 leden. De WSHeeg kent meerdere Nederlands Kampioenen oa in de Randmeer, Olympiajol en op IFKS skûtsjes. Verder organiseert WSHeeg meerdere NK’s en in het bijzonder het Nederlands Studenten Kampioenschap.', null, '13.Heeg_.png');
INSERT INTO `saillingcrews` VALUES ('14', 'WSV Het Witte Huis', 'HWH', null, '“Het Witte Huis” (HWH) is ontstaan in 1930 en sinds 1935 aangesloten bij het  Watersport Verbond . HWH behoort tot de 9 grootste wedstrijdgevende zeilverenigingen van Nederland met ca.300 leden. HWH kent een gezellig verenigingsleven waaraan vele leden hun steentje bijdragen met activiteiten die variëren van het geven van lessen aan de jeugd , het organiseren van grote zeilevenementen en HWH-wedstrijden, alsmede gecombineerde wedstrijden samen met de Loosdrechtse zusterverenigingen tot en met het runnen van het clubhuis.\r\nBij onze vereniging staat wedstrijdzeilen centraal. Mede daardoor telt HWH veel jonge (en oudere) talenten. Maar bovenal staat het plezier in het zeilen voorop!', null, '14.Wolphaarts.png');
INSERT INTO `saillingcrews` VALUES ('15', 'Braassemermeer', 'Braassemermeer', null, 'Op 22 maart 1918 komt een aantal inwoners van Roelofarendsveen bijeen om een zeilvereniging op te richten met het doel wedstrijden te organiseren. Al in de zomer van het zelfde jaar worden de eerste wedstrijden door deze zeilvereniging, die de naam “Steeds Sneller” krijgt, daadwerkelijk georganiseerd. Eind 1922 wordt besloten de naam “Steeds Sneller” te wijzigen in Zeilvereniging Braassemermeer. Twee jaar later sluit de vereniging zich aan bij de “Verbondenen Zeilverenigingen” nu beter bekend als het KNWV en tevens wordt Koninklijke goedkeuring van de inmiddels opgemaakte statuten aangevraagd.', null, '15.Braassem.png');
INSERT INTO `saillingcrews` VALUES ('16', 'WV Breskens', 'WV Breskens', null, 'Watersportvereniging Breskens is een enthousiaste vereniging met bijna 400 leden. De haven ligt op loopafstand van het centrum en u ligt er lekker beschut. Watersportvereniging Breskens ondersteunt bij evenementen als United 4 Sailing, Tour de France à la Voile, Delta Combi en niet in de laatste plaats het Breskens Sailing Weekend. De Westerschelde is het zuidelijke zeewater van het Deltagebied tussen Zuid-Beveland en Zeeuws-Vlaanderen. De zeearm heeft een open verbinding met de Noordzee en de Schelde.', null, '16.Breskens.png');
INSERT INTO `saillingcrews` VALUES ('17', 'WSV Wolphaartsdijk', 'WSV Wolphaartsdijk', null, 'De Zeeuwse watersportvereniging WSV Wolphaartsdijk. De WSVW is een vereniging met ruim 900 leden die beschikt over 480 ligplaatsen aan het Veerse Meer, nabij Wolphaartsdijk. De WSVW werd opgericht op 13 maart 1961. De WSVW staat bekend als een “familiehaven”. Hoeveel jonge kinderen hebben al niet de eerste beginselen van het zeilen geleerd onder leiding van de trainers van de jeugdcommissie? Door de wedstrijdcommissie worden zowel in de zomer als in de winter clubwedstrijden georganiseerd.', null, '17.DenBosch.png');
INSERT INTO `saillingcrews` VALUES ('18', 'Zeilteam Westeinder', 'Zeilteam Westeinder', null, 'Zeilteam Westeinder is een gecombineerd team van leden van WV de Nieuwe Meer en WV Aalsmeer.  Het team komt voort uit de stichting.Westeinder Zeilwedstrijden (WZW). Een stichting waarin een aantal lokale watersportverenigingen deelnemen. Via Westeinder Zeilwedstrijden bundelen de deelnemende verenigingen hun krachten op het gebied van de wedstrijdzeilsport. Al 70 jaar lang organiseert Westeinder Zeilwedstrijden wedstrijden op de Westeinderplassen; van de Combi Westeinder voor jeugdzeilers uit de regio Amsterdam tot Nederlandse Kampioenschappen en Grand Prix voor nationale en internationale klassen als de Regenboog en de Draak en rond- en platbodemwedstrijden.', null, '18.Westeinder.png');
